"""Add due_date to reservations

Revision ID: 0567ff285b1e
Revises: c61a725cfe6b
Create Date: 2025-05-11 09:57:35.219407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0567ff285b1e'
down_revision = 'c61a725cfe6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
