"""Add DeletedUser table

Revision ID: c61a725cfe6b
Revises: e81176111be1
Create Date: 2025-05-10 14:35:33.145215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61a725cfe6b'
down_revision = 'e81176111be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deleted_users')
    # ### end Alembic commands ###
